### ISSUE TITLE
Pip-install from git always gives the dirty version

### ISSUE THREAD

**Issue by ShihHsuanChen** [dolfinus/setuptools-git-versioning#17]
Hi, I follow the example to setup my `setup.py` as following:
```python=
setuptools.setup(
    ...
    version_config={
        "template": "{tag}"
        "dev_template": "{tag}.dev",
        "dev_template": "{tag}.dirty",
    },
    setup_requires=['setuptools-git-versioning'],
    ...
)
```
When I do `pip install git+http://..../myproj.git@0.0.1`, the installed version is always `0.0.1.dirty`. 
It took me a few tries to fix the problem. Finally the following two ways work:
1. Preinstall `setuptools_git_versioning==1.4.0`, or
2. Add a `pyproject.toml` file in my project
```toml
[build-system]
requires = [
     "setuptools-git-versioning==1.4.0" 
]
build-backend = "setuptools.build_meta"
```
So probably the auto-downloaded one is not the latest version?
