### ISSUE TITLE
InvalidVersion when the tag contains "devx"

### ISSUE THREAD

**Issue by boldchan** [dolfinus/setuptools-git-versioning#99]
I'm following this tutorial: https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/tag/tag_release.html

I use the following pyproject.toml
```toml
[build-system]
requires = ["setuptools>=41", "wheel", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true

[project]
name = "TestRepo"
dynamic = ["version"]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
```

and I add a tag `1.1.5.dev1` to my current `develop` branch. and I run `setuptools-git-versioning`
then I receive packaging.version.InvalidVersion: Invalid version: '1.1.5.dev1.post0+git.cc28ba4c.dirty'

isn't 1.1.5.dev1 a compliant version name?
